platform :ios, '10.0'

target 'AppTest' do
  use_frameworks!

  # Pods for AppTest
  pod 'Alamofire'

  target 'AppTestTests' do
    inherit! :search_paths
    pod 'Mockingjay'
    pod 'Quick'
    pod 'Nimble'
  end

  target 'AppTestUITests' do
    # Pods for testing
  end

end
